# 初识numpy

In [2]:
import numpy as np

In [7]:
score = np.array(
[[80, 89, 86, 67, 79],
[78, 97, 89, 67, 81],
[90, 94, 78, 67, 74],
[91, 91, 90, 67, 69],
[76, 87, 75, 67, 86],
[70, 79, 84, 67, 84],
[94, 92, 93, 67, 64],
[86, 85, 83, 67, 80]]
)

In [8]:
score

array([[80, 89, 86, 67, 79],
       [78, 97, 89, 67, 81],
       [90, 94, 78, 67, 74],
       [91, 91, 90, 67, 69],
       [76, 87, 75, 67, 86],
       [70, 79, 84, 67, 84],
       [94, 92, 93, 67, 64],
       [86, 85, 83, 67, 80]])

## ndarray和原生Python效率对比

In [9]:
import random
import time
import numpy as np
a = []
for i in range(100000000):
    a.append(random.random())

# 通过%time魔法方法, 查看当前行的代码运行一次所花费的时间
%time sum1=sum(a)

b=np.array(a)

%time sum2=np.sum(b)

CPU times: user 321 ms, sys: 885 ms, total: 1.21 s
Wall time: 1.69 s
CPU times: user 31.3 ms, sys: 132 ms, total: 163 ms
Wall time: 168 ms


#  ndarray的使用

## 数组的属性

In [10]:
score

array([[80, 89, 86, 67, 79],
       [78, 97, 89, 67, 81],
       [90, 94, 78, 67, 74],
       [91, 91, 90, 67, 69],
       [76, 87, 75, 67, 86],
       [70, 79, 84, 67, 84],
       [94, 92, 93, 67, 64],
       [86, 85, 83, 67, 80]])

In [11]:
score.shape

(8, 5)

In [13]:
score.ndim

2

In [17]:
score.argmax()

6

In [18]:
score.itemsize # 每个元素大小 - 8字节

8

In [19]:
score.dtype # 默认64位int 即 8字节

dtype('int64')

## 数组的形状

In [20]:
a = np.array([1,2,3])

In [21]:
a

array([1, 2, 3])

In [22]:
a.shape

(3,)

In [24]:
b = np.array([[1, 2, 3], [4, 5, 6]])

In [25]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
b.shape

(2, 3)

In [27]:
c = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

In [28]:
c

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [29]:
c.shape

(2, 2, 3)

## 数组的类型

In [30]:
b = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float32)  # dtype 即设置的元素类型

In [31]:
b

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [34]:
arr = np.array(["pythonIiiii", "hello", "I"], dtype=np.string_) # dtype 即设置的元素类型 这里s7表示最长的字符串

In [35]:
arr

array([b'pythonIiiii', b'hello', b'I'], dtype='|S11')