In [2]:
import numpy as np

# 逻辑运算

In [5]:
score = np.random.randint(40,100,(10,5))
score

array([[88, 49, 45, 44, 89],
       [48, 91, 46, 92, 94],
       [77, 49, 50, 41, 94],
       [88, 76, 68, 92, 99],
       [76, 77, 88, 90, 51],
       [67, 61, 91, 78, 87],
       [73, 49, 42, 75, 47],
       [98, 95, 48, 97, 56],
       [42, 71, 82, 72, 80],
       [88, 43, 69, 95, 81]])

In [6]:
test_score = score[6:, 0:5] # 后四组数据的前五个数据

In [8]:
test_score

array([[73, 49, 42, 75, 47],
       [98, 95, 48, 97, 56],
       [42, 71, 82, 72, 80],
       [88, 43, 69, 95, 81]])

In [9]:
test_score > 60

array([[ True, False, False,  True, False],
       [ True,  True, False,  True, False],
       [False,  True,  True,  True,  True],
       [ True, False,  True,  True,  True]])

In [10]:
test_score[test_score > 60] = 1

In [11]:
test_score

array([[ 1, 49, 42,  1, 47],
       [ 1,  1, 48,  1, 56],
       [42,  1,  1,  1,  1],
       [ 1, 43,  1,  1,  1]])

# 通用判断函数

In [12]:
np.all(score[0:2, :] > 60) # 前两行的所有元素是不是全大于 60 ，是则 true 否则 false

False

In [14]:
score

array([[88, 49, 45, 44, 89],
       [48, 91, 46, 92, 94],
       [77, 49, 50, 41, 94],
       [88, 76, 68, 92, 99],
       [76, 77, 88, 90, 51],
       [67, 61, 91, 78, 87],
       [ 1, 49, 42,  1, 47],
       [ 1,  1, 48,  1, 56],
       [42,  1,  1,  1,  1],
       [ 1, 43,  1,  1,  1]])

In [15]:
np.any(score[0:2, :] > 90) # 前两行的所有元素 是否存在小于 90的元素 ，是则 true 否则 false

True

# np.where（三元运算符）

In [17]:
tmp = score[:4,:4] # 前4行 前4列的元素

In [18]:
tmp

array([[88, 49, 45, 44],
       [48, 91, 46, 92],
       [77, 49, 50, 41],
       [88, 76, 68, 92]])

In [19]:
np.where(tmp > 60, 1, 0) # 在tmp中找到大于 60 的元素 ，将其置为1，否则置为0

array([[1, 0, 0, 0],
       [0, 1, 0, 1],
       [1, 0, 0, 0],
       [1, 1, 1, 1]])

In [20]:
np.where(np.logical_and(tmp > 60, tmp < 90), 1, 0) # 在tmp中找到大于 60 且小于 90 的元素 ，将其置为1，否则置为0

array([[1, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 1, 1, 0]])

In [21]:
np.where(np.logical_or(tmp < 60, tmp > 90), 1, 0) # 在tmp中找到小于于 60 或者大于 90 的元素 ，将其置为1，否则置为0

array([[0, 1, 1, 1],
       [1, 1, 1, 1],
       [0, 1, 1, 1],
       [0, 0, 0, 1]])

# 统计运算

In [22]:
temp = score[:4, :]

In [23]:
temp

array([[88, 49, 45, 44, 89],
       [48, 91, 46, 92, 94],
       [77, 49, 50, 41, 94],
       [88, 76, 68, 92, 99]])

In [24]:
np.max(temp) # 返回最大值

99

In [26]:
np.mean(temp)

71.0

In [27]:
np.max(temp, axis=0)  # 每一列的最大值

array([88, 91, 68, 92, 99])

In [28]:
np.max(temp, axis=1)  # 每一行的最大值

array([89, 94, 94, 99])

In [29]:
np.argmax(temp) # 返回最大值的下标

19

In [31]:
np.argmax(temp, axis=0)  # 返回每一列最大值的下标

array([0, 1, 3, 1, 3])

In [33]:
np.argmin(temp, axis=1) # 返回每一行最小值的下标

array([3, 2, 3, 2])

# 数组间的运算

In [3]:
a = np.array([[1,2,3],[3,4,5]])

In [4]:
a

array([[1, 2, 3],
       [3, 4, 5]])

In [5]:
a+2

array([[3, 4, 5],
       [5, 6, 7]])

In [6]:
a-1

array([[0, 1, 2],
       [2, 3, 4]])

In [7]:
a/2

array([[0.5, 1. , 1.5],
       [1.5, 2. , 2.5]])

In [8]:
a*3

array([[ 3,  6,  9],
       [ 9, 12, 15]])

In [9]:
a = [1,2,3]
a * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [10]:
arr1 = np.array([[1, 2, 3, 2, 1, 4], [5, 6, 1, 2, 3, 1]])
arr2 = np.array([[1, 2, 3, 4], [3, 4, 5, 6]])

In [12]:
# arr1 + arr2 
# operands could not be broadcast together with shapes (2,6) (2,4) 

In [14]:
arr1 = np.array([[1, 2, 3, 2, 1, 4], [5, 6, 1, 2, 3, 1]])
arr2 = np.array([[1], [3]])

In [15]:
arr1.shape

(2, 6)

In [16]:
arr2.shape

(2, 1)

In [17]:
# 1.维度相等 2.(.shape对应的维度为1，也可以)

In [18]:
arr1 + arr2

array([[2, 3, 4, 3, 2, 5],
       [8, 9, 4, 5, 6, 4]])

# 矩阵运算

In [19]:
a = np.array([[80, 86],
[82, 80],
[85, 78],
[90, 90],
[86, 82],
[82, 90],
[78, 80],
[92, 94]])

In [20]:
a

array([[80, 86],
       [82, 80],
       [85, 78],
       [90, 90],
       [86, 82],
       [82, 90],
       [78, 80],
       [92, 94]])

In [22]:
b = np.array([[0.7], [0.3]])

In [23]:
np.dot(a, b)

array([[81.8],
       [81.4],
       [82.9],
       [90. ],
       [84.8],
       [84.4],
       [78.6],
       [92.6]])

In [24]:
np.matmul(a, b)

array([[81.8],
       [81.4],
       [82.9],
       [90. ],
       [84.8],
       [84.4],
       [78.6],
       [92.6]])

In [25]:
c = 10

In [26]:
np.dot(c, a)

array([[800, 860],
       [820, 800],
       [850, 780],
       [900, 900],
       [860, 820],
       [820, 900],
       [780, 800],
       [920, 940]])

In [28]:
# np.matmul(c, a) # matmul不支持矩阵和标量的乘法